#ifndef __SETTINGS_H
#define __SETTINGS_H

#define RADIO_RUEDAS 0.022
#define DISTANCIA_ENTRE_EJES 0.093

#define PASOS_POR_VUELTA 357.7
#define LONGITUD_PASO_ENCODER ((2 * PI * RADIO_RUEDAS) / PASOS_POR_VUELTA)

#define FRECUENCIA_TIMER 0.001
#define INTERVALO_TCNT1 (1.0/(OCR1A / FRECUENCIA_TIMER))

#endif /* ifndef SETTINGS_H

 */
