#ifndef __SETTINGS_H
#define __SETTINGS_H

#define RADIO_RUEDAS 0.021692
#define DISTANCIA_ENTRE_RUEDAS (0.067753)

#define PASOS_POR_VUELTA 357.7
#define LONGITUD_PASO_ENCODER ((2 * PI * RADIO_RUEDAS) / PASOS_POR_VUELTA)

#define PERIODO_TIMER 0.001
#define PERIODO_CICLO (PERIODO_TIMER * NUMERO_ESTADOS)
#define NUMERO_ESTADOS 4
#define OCR1A_POR_CICLO (OCR1A * NUMERO_ESTADOS)

#define VELOCIDAD_INDEFINIDA 0xFFFFFFFF

#define KP_LINEAL -0.6
#define KD_LINEAL -0.0
#define KI_LINEAL -0.0

#endif /* ifndef SETTINGS_H

 */
